### PR TITLE
Excel to JSON conversion scripts for twitter handles and articles.

### PR DESCRIPTION
**Pull request by RaiyanRahman**

### CODE REVIEW

**Comment by RaiyanRahman** [comment]
Tested and works. Resulting JSONs provided.

**Comment by sherry13131** [comment]
Twitter Handles JSON headers should add some more fields (Source/Referring and Domain), according to the latest update of the excel sheet. The JSON structure of the articles conversion should be fine.

**Comment by RaiyanRahman** [comment]
Has been updated with source/referring properties in the JSON.

**Comment by sherry13131** [comment]
I might actually need an actual function for me to call it and run the conversion script for both articles and twitter. In your code, you are using `__name__ == '__main__'` to run the code, it will be easier for me to implement if it is a function with parameters (like filename as the functions need).

**Comment by sherry13131** [comment]
Also, I tried to pass the filename of the excel file, the relative path from the conversion script and the relative path from my code and the absolute path of the excel file to run the script. It doesn't work. Would you mind tell me how you test the code? I have installed openpyxl. Thanks.

**Comment by RaiyanRahman** [comment]
> I might actually need an actual function for me to call it and run the conversion script for both articles and twitter. In your code, you are using `__name__ == '__main__'` to run the code, it will be easier for me to implement if it is a function with parameters (like filename as the functions need).

You should still be able to import it into where you need to use it and just run it like a function.
I'll update the name == main place to not have a hardcoded value, I did that for testing and forgot to take it back out.

**Comment by RaiyanRahman** [comment]
> Also, I tried to pass the filename of the excel file, the relative path from the conversion script and the relative path from my code and the absolute path of the excel file to run the script. It doesn't work. Would you mind tell me how you test the code? I have installed openpyxl, and all the uploaded files I put them in "/Voyage/Frontend/uploads/". Thanks.

All you need to use the conversion script is openpyxl, which you've installed. It should work after that. Feel free to move the actual python files of the conversion scripts around if they are more convenient for you.
I tested my code out with placing the excel files in a separate directory and it still worked with longer and relative file paths.

I would suggest trying to import the function through these lines:
from src.excel_to_json_script.articles_conversion_script import convert_articles_to_json
from src.excel_to_json_script.twitter_handles_conversion_script import convert_twitter_handles_to_json

After that, you should just be able to call it like a normal function:
convert_twitter_handles_to_json('../../Frontend/uploads/Israeli_Palestinian Twitter Handles_Y.xlsx')
convert_articles_to_json('../../Frontend/uploads/NEWIsraeli_Palestinian English News Sites.xlsx')

These will create the JSON files twitter_handles.json and articles.json in the src/excel_to_json_script folder.
Please let me know if that helped.

**Comment by sherry13131** [comment]
The lines that you suggested to me for import the functions was helpful. I pass the absolute path of the excel file for the conversion function and it works. It does not work for me yesterday since there are spaces in the file name and I have to decode those '%20' back to space. Thanks.

**Comment by sherry13131** [comment]
I think we can merge since I was able to connect for the articles conversion function. Twitter conversion function should be fine as well.

**Pull request merged**
